### ISSUE TITLE
Update individual beacons directly

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#260]
Do not use `tryMulticall`. See: https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1713434599386719

**Comment by bbenligiray** [comment]
I was busy with the migration outage while writing to that thread. There are two options with the gas limit, either don't estimate it at all and omit it in the transaction (so that ethers does it under the hood), or do it explicitly. When we do it explicitly, we can just estimate it and use it exactly, we wouldn't need the multicall-tryMulticall trick or the 1.1 multiplier.

**Comment by Siegrift** [comment]
> There are two options with the gas limit, either don't estimate it at all and omit it in the transaction (so that ethers does it under the hood), or do it explicitly.

Yes, that's basically what I was asking.

> When we do it explicitly, we can just estimate it and use it exactly, we wouldn't need the multicall-tryMulticall trick or the 1.1 multiplier.

So that's basically what you're saying in the thread. I am not sure what you mean by your comment. Is it just for additional clarity?

**Comment by bbenligiray** [comment]
Yes, just saying the same stuff but more explicitly
